### ISSUE TITLE
Improve process of reporting broken links

### ISSUE THREAD

**Issue by cjcenizal** [vectara/vectara-docs#134]
Currently, the 404 page looks like this:

![image](https://github.com/vectara/vectara-docs/assets/1238659/97a56c56-55be-4e60-ba82-21290b8d2b81)

This isn't very helpful if the link comes from Google, which is the most likely cause. It also doesn't acknowledge the fact that the link broke because _we_ broke it. 😂 

I suggest we replace this guidance with:

> Sorry, we accidentally broke this link. Could you please [let us know](https://github.com/vectara/vectara-docs/issues/new?assignees=&labels=bug&projects=&template=bug.yml) so we can fix it?

I think we should create a new issue template specifically for broken links and change the link to point to that template.

Once @mrderyk has shipped docs search, we can update the above message by appending it with:

> You can also search for this topic in the search box above.

**Comment by eskibars** [comment]
In theory, if we're following good development practices, this should be fairly rare at least for us to be the reason for it.  That is:
* Docusaurus fails the build if it finds broken links, so as long as builds are being tested locally before they're getting pushed, we shouldn't have broken links within the docs.  (The exception is from API playground to other docs, where we're using fully qualified URLs instead of relative URLs)
* We should be checking URLs we're sending from other locations (e.g. console, website) before pushing commits that break the docs.  This should be part of the review process

That said, this looks not very intuitive for those of us that have never used React, but https://stackoverflow.com/questions/71370916/how-do-i-customise-the-404-page looks like instructions on how to do it @pwoznic .  @cjcenizal  you might actually be in a better position to help do this

**Comment by cjcenizal** [comment]
@eskibars One other situation in which broken links can occur is if Google indexes a page which we then rename or delete, and we forget to add a redirect. Of all 404s, this will likely be the most common.
