### ISSUE TITLE
Surface pages no more than once in the side nav

### ISSUE THREAD

**Issue by cjcenizal** [vectara/vectara-docs#173]
It's super-disorienting when the same page comes up multiple places in the side nav. It's like an identical page coming up twice in a book -- you lose track of where you are and get confused.

One example of this is https://docs.vectara.com/docs/getting-started-samples/queryDataApiKey.php, which is linked to in at least two places:

![image](https://github.com/vectara/vectara-docs/assets/1238659/73c6a945-cda6-4bfd-87f9-f3b52cb745d5)

**Comment by eskibars** [comment]
Since I did this, I think we should at least have a discussion first on whether it is a bug or not, and what the best way to solve it might be.

The reason I did this is mostly because it's incredibly difficult for a user to know exactly where to find something, with or without a good ToC.  I usually go to the sidebar, look at the list of topics, expand out the ones that look most sensible, and then try to find the right sub-page.  I added several links in multiple places in the ToC because it felt like "oh, would a user be looking for this bit of code we have in the auth section or in a query code samples section?"  I couldn't think of which place *most* users would go to (though I, like I'm sure everyone, has opinions on that).  So I just added a link in both places.  I actually saw it as a benefit that it would then expand both sections, since it meant expanding areas of the docs that I would be interested in.

That said, since we've had several points of confusion on the code samples in the docs, maybe the right thing to do is to eliminate all of the code samples entirely from docs and instead put links into the `getting-started` repo instead.  These are kind of a pain to maintain and it's not clear to me that we can resolve and maintain the issues that have been brought up with the code samples in the docs anyway in the next 12+ months

**Comment by cjcenizal** [comment]
> The reason I did this is mostly because it's incredibly difficult for a user to know exactly where to find something, with or without a good ToC.

True! I think the new site search will help a lot with this.

> I added several links in multiple places

I'm a fan of cross-links, but typically from the content instead of the side-nav. This enables the ToC to act as a map (wherein each location is unique) while enabling users to discover useful information from multiple locations. https://react.dev/learn/responding-to-events is a great example of this approach. The page contains cross-links to:

* https://react.dev/learn/passing-props-to-a-component (twice!)
* https://react.dev/learn/render-and-commit
* https://react.dev/learn/javascript-in-jsx-with-curly-braces
* https://react.dev/reference/react-dom/components/common#common-props
* https://react.dev/learn/keeping-components-pure
* https://react.dev/learn/state-a-components-memory (this is a standalone link to the very next page in the series)

These copious cross-links help someone who lands on this page learn about the surrounding concepts that are needed to fully understand and leverage the page's primary concept.

**Comment by eskibars** [comment]
This was done a bit ago, but this ticket is outstanding as still open.  Closing
