### ISSUE TITLE
Create page dedicated to Factual Consistency Score

### ISSUE THREAD

**Issue by cjcenizal** [vectara/vectara-docs#271]
I think we currently describe FCS in four places:
* https://docs.vectara.com/docs/api-reference/search-apis/stream-query#factual-consistency-score
* https://docs.vectara.com/docs/api-reference/search-apis/search#factual-consistency-score
* https://docs.vectara.com/docs/learn/grounded-generation/grounded-generation-overview#factual-consistency-score---evaluate-hallucinations
* https://docs.vectara.com/docs/console-ui/corpus-query-configuration#configure-evaluation

The first two links seem like they have the most thorough description of FCS, but they're somewhat hidden within API Reference > Query APIs > Stream Query API / Query API.

I think a page dedicated to FCS will help improve discoverability, and provide an opportunity to reduce the amount of FCS info in the other pages because they can cross-link instead.

**Comment by pwoznic** [comment]
Thanks, CJ! I'm actually making lots of IA changes in #259 ([draft deploy preview](https://deploy-preview-259--luxury-shortbread-acee05.netlify.app/docs/learn/hallucination-evaluation)) which will have a dedicated page for FCS and I'm hoping to have it completed next week. It's a WIP since there's still a bit of renaming/reorganizing to go but I wanted to let you know it's on the radar.

**Comment by cjcenizal** [comment]
Wonderful! Thanks, Paul!
